//application context
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const DELETE_APPLICATION = 'DELETE_APPLICATION';
export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const CLEAR_APPLICATIONS = 'CLEAR_APPLICATIONS';
export const APPLICATION_ERROR = 'APPLICATION_ERROR';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const FILTER_APPLICATIONS = 'FILTER_APPLICATIONS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//auth context
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
